package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseAccountRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountRole extends BaseAccountRole<AccountRole> {
	
}
