package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	
}
