package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseApplication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Application extends BaseApplication<Application> {
	
}
