package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseArticleComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleComment extends BaseArticleComment<ArticleComment> {
	
}
