package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	
}
