package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseAuthCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthCode extends BaseAuthCode<AuthCode> {
	
}
