package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseIssueComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IssueComment extends BaseIssueComment<IssueComment> {
	
}
