package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseParagraphComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParagraphComment extends BaseParagraphComment<ParagraphComment> {
	
}
