package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseSection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Section extends BaseSection<Section> {
	
}
