package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {
	
}
