package com.moshi.common.model2;

import com.moshi.common.model2.base.BaseSubscription;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subscription extends BaseSubscription<Subscription> {
	
}
