package com.moshi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApplication<M extends BaseApplication<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	/**
	 * 类别
	 */
	public void setCategory(java.lang.Integer category) {
		set("category", category);
	}
	
	/**
	 * 类别
	 */
	public java.lang.Integer getCategory() {
		return getInt("category");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 管理员的回应
	 */
	public void setReply(java.lang.String reply) {
		set("reply", reply);
	}
	
	/**
	 * 管理员的回应
	 */
	public java.lang.String getReply() {
		return getStr("reply");
	}

	public void setRefId(java.lang.Integer refId) {
		set("refId", refId);
	}
	
	public java.lang.Integer getRefId() {
		return getInt("refId");
	}

	public void setContentType(java.lang.String contentType) {
		set("contentType", contentType);
	}
	
	public java.lang.String getContentType() {
		return getStr("contentType");
	}

}
