package com.moshi.common.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAudio<M extends BaseAudio<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setResource(java.lang.String resource) {
		set("resource", resource);
	}
	
	public java.lang.String getResource() {
		return getStr("resource");
	}

	public void setRecorder(java.lang.String recorder) {
		set("recorder", recorder);
	}
	
	public java.lang.String getRecorder() {
		return getStr("recorder");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setUploadAt(java.lang.Long uploadAt) {
		set("uploadAt", uploadAt);
	}
	
	public java.lang.Long getUploadAt() {
		return getLong("uploadAt");
	}

}
