package com.moshi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCourseId(java.lang.Integer courseId) {
		set("courseId", courseId);
	}
	
	public java.lang.Integer getCourseId() {
		return getInt("courseId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setPublishAt(java.lang.Long publishAt) {
		set("publishAt", publishAt);
	}
	
	public java.lang.Long getPublishAt() {
		return getLong("publishAt");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setAudioId(java.lang.Integer audioId) {
		set("audioId", audioId);
	}
	
	public java.lang.Integer getAudioId() {
		return getInt("audioId");
	}

	public void setContentType(java.lang.String contentType) {
		set("contentType", contentType);
	}
	
	public java.lang.String getContentType() {
		return getStr("contentType");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}
	
	public java.lang.String getSummary() {
		return getStr("summary");
	}

	public void setCoverImage(java.lang.String coverImage) {
		set("coverImage", coverImage);
	}
	
	public java.lang.String getCoverImage() {
		return getStr("coverImage");
	}

}
