package com.moshi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 作者id
	 */
	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	/**
	 * 作者id
	 */
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	/**
	 * 专栏名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 专栏名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 专栏简介
	 */
	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}
	
	/**
	 * 专栏简介
	 */
	public java.lang.String getIntroduce() {
		return getStr("introduce");
	}

	public void setShortIntro(java.lang.String shortIntro) {
		set("shortIntro", shortIntro);
	}
	
	public java.lang.String getShortIntro() {
		return getStr("shortIntro");
	}

	public void setIntroduceImage(java.lang.String introduceImage) {
		set("introduceImage", introduceImage);
	}
	
	public java.lang.String getIntroduceImage() {
		return getStr("introduceImage");
	}

	/**
	 * 订阅须知
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 订阅须知
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

	/**
	 * 创建时间
	 */
	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	/**
	 * 发布时间
	 */
	public void setPublishAt(java.lang.Long publishAt) {
		set("publishAt", publishAt);
	}
	
	/**
	 * 发布时间
	 */
	public java.lang.Long getPublishAt() {
		return getLong("publishAt");
	}

	/**
	 * 购买人数
	 */
	public void setBuyerCount(java.lang.Integer buyerCount) {
		set("buyerCount", buyerCount);
	}
	
	/**
	 * 购买人数
	 */
	public java.lang.Integer getBuyerCount() {
		return getInt("buyerCount");
	}

	/**
	 * 课程类型（1：专栏；2：视频）
	 */
	public void setCourseType(java.lang.Integer courseType) {
		set("courseType", courseType);
	}
	
	/**
	 * 课程类型（1：专栏；2：视频）
	 */
	public java.lang.Integer getCourseType() {
		return getInt("courseType");
	}

	/**
	 * 标准价格
	 */
	public void setPrice(java.lang.Double price) {
		set("price", price);
	}
	
	/**
	 * 标准价格
	 */
	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	/**
	 * 优惠价格
	 */
	public void setDiscountedPrice(java.lang.Double discountedPrice) {
		set("discountedPrice", discountedPrice);
	}
	
	/**
	 * 优惠价格
	 */
	public java.lang.Double getDiscountedPrice() {
		return getDouble("discountedPrice");
	}

	/**
	 * 优惠到某时间
	 */
	public void setOfferTo(java.lang.Long offerTo) {
		set("offerTo", offerTo);
	}
	
	/**
	 * 优惠到某时间
	 */
	public java.lang.Long getOfferTo() {
		return getLong("offerTo");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setLectureCount(java.lang.Integer lectureCount) {
		set("lectureCount", lectureCount);
	}
	
	public java.lang.Integer getLectureCount() {
		return getInt("lectureCount");
	}

}
