package com.moshi.common.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCourse<M extends BaseCourse<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}
	
	public java.lang.String getIntroduce() {
		return getStr("introduce");
	}

	public void setShortIntro(java.lang.String shortIntro) {
		set("shortIntro", shortIntro);
	}
	
	public java.lang.String getShortIntro() {
		return getStr("shortIntro");
	}

	public void setIntroduceImage(java.lang.String introduceImage) {
		set("introduceImage", introduceImage);
	}
	
	public java.lang.String getIntroduceImage() {
		return getStr("introduceImage");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	public java.lang.String getNote() {
		return getStr("note");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	public void setPublishAt(java.lang.Long publishAt) {
		set("publishAt", publishAt);
	}
	
	public java.lang.Long getPublishAt() {
		return getLong("publishAt");
	}

	public void setBuyerCount(java.lang.Integer buyerCount) {
		set("buyerCount", buyerCount);
	}
	
	public java.lang.Integer getBuyerCount() {
		return getInt("buyerCount");
	}

	public void setCourseType(java.lang.Integer courseType) {
		set("courseType", courseType);
	}
	
	public java.lang.Integer getCourseType() {
		return getInt("courseType");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}
	
	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public void setDiscountedPrice(java.lang.Double discountedPrice) {
		set("discountedPrice", discountedPrice);
	}
	
	public java.lang.Double getDiscountedPrice() {
		return getDouble("discountedPrice");
	}

	public void setOfferTo(java.lang.Long offerTo) {
		set("offerTo", offerTo);
	}
	
	public java.lang.Long getOfferTo() {
		return getLong("offerTo");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setLectureCount(java.lang.Integer lectureCount) {
		set("lectureCount", lectureCount);
	}
	
	public java.lang.Integer getLectureCount() {
		return getInt("lectureCount");
	}

}
