package com.moshi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIssue<M extends BaseIssue<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCourseId(java.lang.Integer courseId) {
		set("courseId", courseId);
	}
	
	public java.lang.Integer getCourseId() {
		return getInt("courseId");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setOpenAt(java.lang.Long openAt) {
		set("openAt", openAt);
	}
	
	public java.lang.Long getOpenAt() {
		return getLong("openAt");
	}

	/**
	 * 弃用
	 */
	public void setCloserId(java.lang.Integer closerId) {
		set("closerId", closerId);
	}
	
	/**
	 * 弃用
	 */
	public java.lang.Integer getCloserId() {
		return getInt("closerId");
	}

	public void setCloseAt(java.lang.Long closeAt) {
		set("closeAt", closeAt);
	}
	
	public java.lang.Long getCloseAt() {
		return getLong("closeAt");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
