package com.moshi.common.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoupon<M extends BaseCoupon<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setValue(java.lang.Double value) {
		set("value", value);
	}
	
	public java.lang.Double getValue() {
		return getDouble("value");
	}

	public void setValueType(java.lang.Integer valueType) {
		set("valueType", valueType);
	}
	
	public java.lang.Integer getValueType() {
		return getInt("valueType");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public void setRefId(java.lang.Integer refId) {
		set("refId", refId);
	}
	
	public java.lang.Integer getRefId() {
		return getInt("refId");
	}

	public void setRefType(java.lang.Integer refType) {
		set("refType", refType);
	}
	
	public java.lang.Integer getRefType() {
		return getInt("refType");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	public void setOfferTo(java.lang.Long offerTo) {
		set("offerTo", offerTo);
	}
	
	public java.lang.Long getOfferTo() {
		return getLong("offerTo");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
