package com.moshi.common.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAudio<M extends BaseAudio<M>> extends JbootModel<M> implements IBean {

	public void setArticleId(java.lang.Integer articleId) {
		set("articleId", articleId);
	}
	
	public java.lang.Integer getArticleId() {
		return getInt("articleId");
	}

	public void setResource(java.lang.String resource) {
		set("resource", resource);
	}
	
	public java.lang.String getResource() {
		return getStr("resource");
	}

	public void setReader(java.lang.String reader) {
		set("reader", reader);
	}
	
	public java.lang.String getReader() {
		return getStr("reader");
	}

}
