package com.moshi.common.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setNickName(java.lang.String nickName) {
		set("nickName", nickName);
	}
	
	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public void setRealName(java.lang.String realName) {
		set("realName", realName);
	}
	
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	public void setIdentityNumber(java.lang.String identityNumber) {
		set("identityNumber", identityNumber);
	}
	
	public java.lang.String getIdentityNumber() {
		return getStr("identityNumber");
	}

	public void setAge(java.lang.Long age) {
		set("age", age);
	}
	
	public java.lang.Long getAge() {
		return getLong("age");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}
	
	public java.lang.String getCompany() {
		return getStr("company");
	}

	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public void setPersonalProfile(java.lang.String personalProfile) {
		set("personalProfile", personalProfile);
	}
	
	public java.lang.String getPersonalProfile() {
		return getStr("personalProfile");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setBirthday(java.lang.Long birthday) {
		set("birthday", birthday);
	}
	
	public java.lang.Long getBirthday() {
		return getLong("birthday");
	}

	public void setEducation(java.lang.String education) {
		set("education", education);
	}
	
	public java.lang.String getEducation() {
		return getStr("education");
	}

	public void setProfession(java.lang.String profession) {
		set("profession", profession);
	}
	
	public java.lang.String getProfession() {
		return getStr("profession");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
