package com.moshi.common.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends JbootModel<M> implements IBean {

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public void setPermissionId(java.lang.Integer permissionId) {
		set("permissionId", permissionId);
	}
	
	public java.lang.Integer getPermissionId() {
		return getInt("permissionId");
	}

}
