// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface AccountBaseInfoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.AccountBaseInfoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  com.moshi.im.common.Code getCode();

  /**
   * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
   */
  boolean hasAccount();
  /**
   * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
   */
  com.moshi.im.common.AccountBaseInfo getAccount();
  /**
   * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
   */
  com.moshi.im.common.AccountBaseInfoOrBuilder getAccountOrBuilder();

  /**
   * <code>.com.moshi.im.common.Role role = 3;</code>
   */
  int getRoleValue();
  /**
   * <code>.com.moshi.im.common.Role role = 3;</code>
   */
  com.moshi.im.common.Role getRole();
}
