// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

/**
 * Protobuf type {@code com.moshi.im.common.AccountBaseInfoReply}
 */
public  final class AccountBaseInfoReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.moshi.im.common.AccountBaseInfoReply)
    AccountBaseInfoReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountBaseInfoReply.newBuilder() to construct.
  private AccountBaseInfoReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountBaseInfoReply() {
    code_ = 0;
    role_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccountBaseInfoReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            code_ = rawValue;
            break;
          }
          case 18: {
            com.moshi.im.common.AccountBaseInfo.Builder subBuilder = null;
            if (account_ != null) {
              subBuilder = account_.toBuilder();
            }
            account_ = input.readMessage(com.moshi.im.common.AccountBaseInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(account_);
              account_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            role_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_AccountBaseInfoReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_AccountBaseInfoReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moshi.im.common.AccountBaseInfoReply.class, com.moshi.im.common.AccountBaseInfoReply.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  public int getCodeValue() {
    return code_;
  }
  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  public com.moshi.im.common.Code getCode() {
    @SuppressWarnings("deprecation")
    com.moshi.im.common.Code result = com.moshi.im.common.Code.valueOf(code_);
    return result == null ? com.moshi.im.common.Code.UNRECOGNIZED : result;
  }

  public static final int ACCOUNT_FIELD_NUMBER = 2;
  private com.moshi.im.common.AccountBaseInfo account_;
  /**
   * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
   */
  public boolean hasAccount() {
    return account_ != null;
  }
  /**
   * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
   */
  public com.moshi.im.common.AccountBaseInfo getAccount() {
    return account_ == null ? com.moshi.im.common.AccountBaseInfo.getDefaultInstance() : account_;
  }
  /**
   * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
   */
  public com.moshi.im.common.AccountBaseInfoOrBuilder getAccountOrBuilder() {
    return getAccount();
  }

  public static final int ROLE_FIELD_NUMBER = 3;
  private int role_;
  /**
   * <code>.com.moshi.im.common.Role role = 3;</code>
   */
  public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.com.moshi.im.common.Role role = 3;</code>
   */
  public com.moshi.im.common.Role getRole() {
    @SuppressWarnings("deprecation")
    com.moshi.im.common.Role result = com.moshi.im.common.Role.valueOf(role_);
    return result == null ? com.moshi.im.common.Role.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != com.moshi.im.common.Code.OK.getNumber()) {
      output.writeEnum(1, code_);
    }
    if (account_ != null) {
      output.writeMessage(2, getAccount());
    }
    if (role_ != com.moshi.im.common.Role.CUSTOMER.getNumber()) {
      output.writeEnum(3, role_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != com.moshi.im.common.Code.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, code_);
    }
    if (account_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAccount());
    }
    if (role_ != com.moshi.im.common.Role.CUSTOMER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, role_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moshi.im.common.AccountBaseInfoReply)) {
      return super.equals(obj);
    }
    com.moshi.im.common.AccountBaseInfoReply other = (com.moshi.im.common.AccountBaseInfoReply) obj;

    boolean result = true;
    result = result && code_ == other.code_;
    result = result && (hasAccount() == other.hasAccount());
    if (hasAccount()) {
      result = result && getAccount()
          .equals(other.getAccount());
    }
    result = result && role_ == other.role_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    if (hasAccount()) {
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
    }
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + role_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.AccountBaseInfoReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moshi.im.common.AccountBaseInfoReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.moshi.im.common.AccountBaseInfoReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.moshi.im.common.AccountBaseInfoReply)
      com.moshi.im.common.AccountBaseInfoReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_AccountBaseInfoReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_AccountBaseInfoReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moshi.im.common.AccountBaseInfoReply.class, com.moshi.im.common.AccountBaseInfoReply.Builder.class);
    }

    // Construct using com.moshi.im.common.AccountBaseInfoReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = 0;

      if (accountBuilder_ == null) {
        account_ = null;
      } else {
        account_ = null;
        accountBuilder_ = null;
      }
      role_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_AccountBaseInfoReply_descriptor;
    }

    @java.lang.Override
    public com.moshi.im.common.AccountBaseInfoReply getDefaultInstanceForType() {
      return com.moshi.im.common.AccountBaseInfoReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.moshi.im.common.AccountBaseInfoReply build() {
      com.moshi.im.common.AccountBaseInfoReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moshi.im.common.AccountBaseInfoReply buildPartial() {
      com.moshi.im.common.AccountBaseInfoReply result = new com.moshi.im.common.AccountBaseInfoReply(this);
      result.code_ = code_;
      if (accountBuilder_ == null) {
        result.account_ = account_;
      } else {
        result.account_ = accountBuilder_.build();
      }
      result.role_ = role_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moshi.im.common.AccountBaseInfoReply) {
        return mergeFrom((com.moshi.im.common.AccountBaseInfoReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moshi.im.common.AccountBaseInfoReply other) {
      if (other == com.moshi.im.common.AccountBaseInfoReply.getDefaultInstance()) return this;
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (other.hasAccount()) {
        mergeAccount(other.getAccount());
      }
      if (other.role_ != 0) {
        setRoleValue(other.getRoleValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.moshi.im.common.AccountBaseInfoReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.moshi.im.common.AccountBaseInfoReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int code_ = 0;
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public Builder setCodeValue(int value) {
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public com.moshi.im.common.Code getCode() {
      @SuppressWarnings("deprecation")
      com.moshi.im.common.Code result = com.moshi.im.common.Code.valueOf(code_);
      return result == null ? com.moshi.im.common.Code.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public Builder setCode(com.moshi.im.common.Code value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private com.moshi.im.common.AccountBaseInfo account_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moshi.im.common.AccountBaseInfo, com.moshi.im.common.AccountBaseInfo.Builder, com.moshi.im.common.AccountBaseInfoOrBuilder> accountBuilder_;
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    public boolean hasAccount() {
      return accountBuilder_ != null || account_ != null;
    }
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    public com.moshi.im.common.AccountBaseInfo getAccount() {
      if (accountBuilder_ == null) {
        return account_ == null ? com.moshi.im.common.AccountBaseInfo.getDefaultInstance() : account_;
      } else {
        return accountBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    public Builder setAccount(com.moshi.im.common.AccountBaseInfo value) {
      if (accountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        account_ = value;
        onChanged();
      } else {
        accountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    public Builder setAccount(
        com.moshi.im.common.AccountBaseInfo.Builder builderForValue) {
      if (accountBuilder_ == null) {
        account_ = builderForValue.build();
        onChanged();
      } else {
        accountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    public Builder mergeAccount(com.moshi.im.common.AccountBaseInfo value) {
      if (accountBuilder_ == null) {
        if (account_ != null) {
          account_ =
            com.moshi.im.common.AccountBaseInfo.newBuilder(account_).mergeFrom(value).buildPartial();
        } else {
          account_ = value;
        }
        onChanged();
      } else {
        accountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    public Builder clearAccount() {
      if (accountBuilder_ == null) {
        account_ = null;
        onChanged();
      } else {
        account_ = null;
        accountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    public com.moshi.im.common.AccountBaseInfo.Builder getAccountBuilder() {
      
      onChanged();
      return getAccountFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    public com.moshi.im.common.AccountBaseInfoOrBuilder getAccountOrBuilder() {
      if (accountBuilder_ != null) {
        return accountBuilder_.getMessageOrBuilder();
      } else {
        return account_ == null ?
            com.moshi.im.common.AccountBaseInfo.getDefaultInstance() : account_;
      }
    }
    /**
     * <code>.com.moshi.im.common.AccountBaseInfo account = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moshi.im.common.AccountBaseInfo, com.moshi.im.common.AccountBaseInfo.Builder, com.moshi.im.common.AccountBaseInfoOrBuilder> 
        getAccountFieldBuilder() {
      if (accountBuilder_ == null) {
        accountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moshi.im.common.AccountBaseInfo, com.moshi.im.common.AccountBaseInfo.Builder, com.moshi.im.common.AccountBaseInfoOrBuilder>(
                getAccount(),
                getParentForChildren(),
                isClean());
        account_ = null;
      }
      return accountBuilder_;
    }

    private int role_ = 0;
    /**
     * <code>.com.moshi.im.common.Role role = 3;</code>
     */
    public int getRoleValue() {
      return role_;
    }
    /**
     * <code>.com.moshi.im.common.Role role = 3;</code>
     */
    public Builder setRoleValue(int value) {
      role_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.moshi.im.common.Role role = 3;</code>
     */
    public com.moshi.im.common.Role getRole() {
      @SuppressWarnings("deprecation")
      com.moshi.im.common.Role result = com.moshi.im.common.Role.valueOf(role_);
      return result == null ? com.moshi.im.common.Role.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.moshi.im.common.Role role = 3;</code>
     */
    public Builder setRole(com.moshi.im.common.Role value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      role_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.moshi.im.common.Role role = 3;</code>
     */
    public Builder clearRole() {
      
      role_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.moshi.im.common.AccountBaseInfoReply)
  }

  // @@protoc_insertion_point(class_scope:com.moshi.im.common.AccountBaseInfoReply)
  private static final com.moshi.im.common.AccountBaseInfoReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moshi.im.common.AccountBaseInfoReply();
  }

  public static com.moshi.im.common.AccountBaseInfoReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountBaseInfoReply>
      PARSER = new com.google.protobuf.AbstractParser<AccountBaseInfoReply>() {
    @java.lang.Override
    public AccountBaseInfoReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AccountBaseInfoReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccountBaseInfoReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountBaseInfoReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moshi.im.common.AccountBaseInfoReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

