// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface AuthReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.AuthReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  com.moshi.im.common.Code getCode();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
