// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface CourseIfSubscribedReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.CourseIfSubscribedReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  com.moshi.im.common.Code getCode();

  /**
   * <code>.com.moshi.im.common.Course course = 2;</code>
   */
  boolean hasCourse();
  /**
   * <code>.com.moshi.im.common.Course course = 2;</code>
   */
  com.moshi.im.common.Course getCourse();
  /**
   * <code>.com.moshi.im.common.Course course = 2;</code>
   */
  com.moshi.im.common.CourseOrBuilder getCourseOrBuilder();
}
