// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 accountId = 2;</code>
   */
  int getAccountId();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string shortIntro = 4;</code>
   */
  java.lang.String getShortIntro();
  /**
   * <code>string shortIntro = 4;</code>
   */
  com.google.protobuf.ByteString
      getShortIntroBytes();

  /**
   * <code>string introduceImage = 5;</code>
   */
  java.lang.String getIntroduceImage();
  /**
   * <code>string introduceImage = 5;</code>
   */
  com.google.protobuf.ByteString
      getIntroduceImageBytes();

  /**
   * <code>string courseType = 6;</code>
   */
  java.lang.String getCourseType();
  /**
   * <code>string courseType = 6;</code>
   */
  com.google.protobuf.ByteString
      getCourseTypeBytes();

  /**
   * <code>int32 status = 7;</code>
   */
  int getStatus();
}
