// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface CourseIfSubscribedReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.CourseIfSubscribedReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 courseId = 1;</code>
   */
  int getCourseId();

  /**
   * <code>int32 accountId = 2;</code>
   */
  int getAccountId();
}
