// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

/**
 * Protobuf type {@code com.moshi.im.common.Course}
 */
public  final class Course extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.moshi.im.common.Course)
    CourseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Course.newBuilder() to construct.
  private Course(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Course() {
    id_ = 0;
    accountId_ = 0;
    name_ = "";
    shortIntro_ = "";
    introduceImage_ = "";
    courseType_ = "";
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Course(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            accountId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            shortIntro_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            introduceImage_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            courseType_ = s;
            break;
          }
          case 56: {

            status_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_Course_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_Course_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moshi.im.common.Course.class, com.moshi.im.common.Course.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 2;
  private int accountId_;
  /**
   * <code>int32 accountId = 2;</code>
   */
  public int getAccountId() {
    return accountId_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHORTINTRO_FIELD_NUMBER = 4;
  private volatile java.lang.Object shortIntro_;
  /**
   * <code>string shortIntro = 4;</code>
   */
  public java.lang.String getShortIntro() {
    java.lang.Object ref = shortIntro_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shortIntro_ = s;
      return s;
    }
  }
  /**
   * <code>string shortIntro = 4;</code>
   */
  public com.google.protobuf.ByteString
      getShortIntroBytes() {
    java.lang.Object ref = shortIntro_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shortIntro_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRODUCEIMAGE_FIELD_NUMBER = 5;
  private volatile java.lang.Object introduceImage_;
  /**
   * <code>string introduceImage = 5;</code>
   */
  public java.lang.String getIntroduceImage() {
    java.lang.Object ref = introduceImage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introduceImage_ = s;
      return s;
    }
  }
  /**
   * <code>string introduceImage = 5;</code>
   */
  public com.google.protobuf.ByteString
      getIntroduceImageBytes() {
    java.lang.Object ref = introduceImage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introduceImage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COURSETYPE_FIELD_NUMBER = 6;
  private volatile java.lang.Object courseType_;
  /**
   * <code>string courseType = 6;</code>
   */
  public java.lang.String getCourseType() {
    java.lang.Object ref = courseType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      courseType_ = s;
      return s;
    }
  }
  /**
   * <code>string courseType = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCourseTypeBytes() {
    java.lang.Object ref = courseType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      courseType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  private int status_;
  /**
   * <code>int32 status = 7;</code>
   */
  public int getStatus() {
    return status_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (accountId_ != 0) {
      output.writeInt32(2, accountId_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (!getShortIntroBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, shortIntro_);
    }
    if (!getIntroduceImageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, introduceImage_);
    }
    if (!getCourseTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, courseType_);
    }
    if (status_ != 0) {
      output.writeInt32(7, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (accountId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, accountId_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (!getShortIntroBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, shortIntro_);
    }
    if (!getIntroduceImageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, introduceImage_);
    }
    if (!getCourseTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, courseType_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moshi.im.common.Course)) {
      return super.equals(obj);
    }
    com.moshi.im.common.Course other = (com.moshi.im.common.Course) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getAccountId()
        == other.getAccountId());
    result = result && getName()
        .equals(other.getName());
    result = result && getShortIntro()
        .equals(other.getShortIntro());
    result = result && getIntroduceImage()
        .equals(other.getIntroduceImage());
    result = result && getCourseType()
        .equals(other.getCourseType());
    result = result && (getStatus()
        == other.getStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SHORTINTRO_FIELD_NUMBER;
    hash = (53 * hash) + getShortIntro().hashCode();
    hash = (37 * hash) + INTRODUCEIMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getIntroduceImage().hashCode();
    hash = (37 * hash) + COURSETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCourseType().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moshi.im.common.Course parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.Course parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.Course parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.Course parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.Course parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.Course parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.Course parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.Course parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.Course parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.Course parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.Course parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.Course parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moshi.im.common.Course prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.moshi.im.common.Course}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.moshi.im.common.Course)
      com.moshi.im.common.CourseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_Course_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_Course_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moshi.im.common.Course.class, com.moshi.im.common.Course.Builder.class);
    }

    // Construct using com.moshi.im.common.Course.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      accountId_ = 0;

      name_ = "";

      shortIntro_ = "";

      introduceImage_ = "";

      courseType_ = "";

      status_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_Course_descriptor;
    }

    @java.lang.Override
    public com.moshi.im.common.Course getDefaultInstanceForType() {
      return com.moshi.im.common.Course.getDefaultInstance();
    }

    @java.lang.Override
    public com.moshi.im.common.Course build() {
      com.moshi.im.common.Course result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moshi.im.common.Course buildPartial() {
      com.moshi.im.common.Course result = new com.moshi.im.common.Course(this);
      result.id_ = id_;
      result.accountId_ = accountId_;
      result.name_ = name_;
      result.shortIntro_ = shortIntro_;
      result.introduceImage_ = introduceImage_;
      result.courseType_ = courseType_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moshi.im.common.Course) {
        return mergeFrom((com.moshi.im.common.Course)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moshi.im.common.Course other) {
      if (other == com.moshi.im.common.Course.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getAccountId() != 0) {
        setAccountId(other.getAccountId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getShortIntro().isEmpty()) {
        shortIntro_ = other.shortIntro_;
        onChanged();
      }
      if (!other.getIntroduceImage().isEmpty()) {
        introduceImage_ = other.introduceImage_;
        onChanged();
      }
      if (!other.getCourseType().isEmpty()) {
        courseType_ = other.courseType_;
        onChanged();
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.moshi.im.common.Course parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.moshi.im.common.Course) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int accountId_ ;
    /**
     * <code>int32 accountId = 2;</code>
     */
    public int getAccountId() {
      return accountId_;
    }
    /**
     * <code>int32 accountId = 2;</code>
     */
    public Builder setAccountId(int value) {
      
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 accountId = 2;</code>
     */
    public Builder clearAccountId() {
      
      accountId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object shortIntro_ = "";
    /**
     * <code>string shortIntro = 4;</code>
     */
    public java.lang.String getShortIntro() {
      java.lang.Object ref = shortIntro_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shortIntro_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string shortIntro = 4;</code>
     */
    public com.google.protobuf.ByteString
        getShortIntroBytes() {
      java.lang.Object ref = shortIntro_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortIntro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string shortIntro = 4;</code>
     */
    public Builder setShortIntro(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shortIntro_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string shortIntro = 4;</code>
     */
    public Builder clearShortIntro() {
      
      shortIntro_ = getDefaultInstance().getShortIntro();
      onChanged();
      return this;
    }
    /**
     * <code>string shortIntro = 4;</code>
     */
    public Builder setShortIntroBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shortIntro_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introduceImage_ = "";
    /**
     * <code>string introduceImage = 5;</code>
     */
    public java.lang.String getIntroduceImage() {
      java.lang.Object ref = introduceImage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introduceImage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string introduceImage = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIntroduceImageBytes() {
      java.lang.Object ref = introduceImage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introduceImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string introduceImage = 5;</code>
     */
    public Builder setIntroduceImage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introduceImage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string introduceImage = 5;</code>
     */
    public Builder clearIntroduceImage() {
      
      introduceImage_ = getDefaultInstance().getIntroduceImage();
      onChanged();
      return this;
    }
    /**
     * <code>string introduceImage = 5;</code>
     */
    public Builder setIntroduceImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introduceImage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object courseType_ = "";
    /**
     * <code>string courseType = 6;</code>
     */
    public java.lang.String getCourseType() {
      java.lang.Object ref = courseType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string courseType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCourseTypeBytes() {
      java.lang.Object ref = courseType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string courseType = 6;</code>
     */
    public Builder setCourseType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      courseType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string courseType = 6;</code>
     */
    public Builder clearCourseType() {
      
      courseType_ = getDefaultInstance().getCourseType();
      onChanged();
      return this;
    }
    /**
     * <code>string courseType = 6;</code>
     */
    public Builder setCourseTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      courseType_ = value;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <code>int32 status = 7;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 7;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 7;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.moshi.im.common.Course)
  }

  // @@protoc_insertion_point(class_scope:com.moshi.im.common.Course)
  private static final com.moshi.im.common.Course DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moshi.im.common.Course();
  }

  public static com.moshi.im.common.Course getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Course>
      PARSER = new com.google.protobuf.AbstractParser<Course>() {
    @java.lang.Override
    public Course parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Course(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Course> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Course> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moshi.im.common.Course getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

