// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

/**
 * Protobuf type {@code com.moshi.im.common.CourseIfSubscribedReply}
 */
public  final class CourseIfSubscribedReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.moshi.im.common.CourseIfSubscribedReply)
    CourseIfSubscribedReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CourseIfSubscribedReply.newBuilder() to construct.
  private CourseIfSubscribedReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CourseIfSubscribedReply() {
    code_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CourseIfSubscribedReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            code_ = rawValue;
            break;
          }
          case 18: {
            com.moshi.im.common.Course.Builder subBuilder = null;
            if (course_ != null) {
              subBuilder = course_.toBuilder();
            }
            course_ = input.readMessage(com.moshi.im.common.Course.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(course_);
              course_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_CourseIfSubscribedReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_CourseIfSubscribedReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moshi.im.common.CourseIfSubscribedReply.class, com.moshi.im.common.CourseIfSubscribedReply.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  public int getCodeValue() {
    return code_;
  }
  /**
   * <code>.com.moshi.im.common.Code code = 1;</code>
   */
  public com.moshi.im.common.Code getCode() {
    @SuppressWarnings("deprecation")
    com.moshi.im.common.Code result = com.moshi.im.common.Code.valueOf(code_);
    return result == null ? com.moshi.im.common.Code.UNRECOGNIZED : result;
  }

  public static final int COURSE_FIELD_NUMBER = 2;
  private com.moshi.im.common.Course course_;
  /**
   * <code>.com.moshi.im.common.Course course = 2;</code>
   */
  public boolean hasCourse() {
    return course_ != null;
  }
  /**
   * <code>.com.moshi.im.common.Course course = 2;</code>
   */
  public com.moshi.im.common.Course getCourse() {
    return course_ == null ? com.moshi.im.common.Course.getDefaultInstance() : course_;
  }
  /**
   * <code>.com.moshi.im.common.Course course = 2;</code>
   */
  public com.moshi.im.common.CourseOrBuilder getCourseOrBuilder() {
    return getCourse();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != com.moshi.im.common.Code.OK.getNumber()) {
      output.writeEnum(1, code_);
    }
    if (course_ != null) {
      output.writeMessage(2, getCourse());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != com.moshi.im.common.Code.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, code_);
    }
    if (course_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCourse());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moshi.im.common.CourseIfSubscribedReply)) {
      return super.equals(obj);
    }
    com.moshi.im.common.CourseIfSubscribedReply other = (com.moshi.im.common.CourseIfSubscribedReply) obj;

    boolean result = true;
    result = result && code_ == other.code_;
    result = result && (hasCourse() == other.hasCourse());
    if (hasCourse()) {
      result = result && getCourse()
          .equals(other.getCourse());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    if (hasCourse()) {
      hash = (37 * hash) + COURSE_FIELD_NUMBER;
      hash = (53 * hash) + getCourse().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.CourseIfSubscribedReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moshi.im.common.CourseIfSubscribedReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.moshi.im.common.CourseIfSubscribedReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.moshi.im.common.CourseIfSubscribedReply)
      com.moshi.im.common.CourseIfSubscribedReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_CourseIfSubscribedReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_CourseIfSubscribedReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moshi.im.common.CourseIfSubscribedReply.class, com.moshi.im.common.CourseIfSubscribedReply.Builder.class);
    }

    // Construct using com.moshi.im.common.CourseIfSubscribedReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = 0;

      if (courseBuilder_ == null) {
        course_ = null;
      } else {
        course_ = null;
        courseBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_CourseIfSubscribedReply_descriptor;
    }

    @java.lang.Override
    public com.moshi.im.common.CourseIfSubscribedReply getDefaultInstanceForType() {
      return com.moshi.im.common.CourseIfSubscribedReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.moshi.im.common.CourseIfSubscribedReply build() {
      com.moshi.im.common.CourseIfSubscribedReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moshi.im.common.CourseIfSubscribedReply buildPartial() {
      com.moshi.im.common.CourseIfSubscribedReply result = new com.moshi.im.common.CourseIfSubscribedReply(this);
      result.code_ = code_;
      if (courseBuilder_ == null) {
        result.course_ = course_;
      } else {
        result.course_ = courseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moshi.im.common.CourseIfSubscribedReply) {
        return mergeFrom((com.moshi.im.common.CourseIfSubscribedReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moshi.im.common.CourseIfSubscribedReply other) {
      if (other == com.moshi.im.common.CourseIfSubscribedReply.getDefaultInstance()) return this;
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (other.hasCourse()) {
        mergeCourse(other.getCourse());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.moshi.im.common.CourseIfSubscribedReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.moshi.im.common.CourseIfSubscribedReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int code_ = 0;
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public Builder setCodeValue(int value) {
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public com.moshi.im.common.Code getCode() {
      @SuppressWarnings("deprecation")
      com.moshi.im.common.Code result = com.moshi.im.common.Code.valueOf(code_);
      return result == null ? com.moshi.im.common.Code.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public Builder setCode(com.moshi.im.common.Code value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.moshi.im.common.Code code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private com.moshi.im.common.Course course_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moshi.im.common.Course, com.moshi.im.common.Course.Builder, com.moshi.im.common.CourseOrBuilder> courseBuilder_;
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    public boolean hasCourse() {
      return courseBuilder_ != null || course_ != null;
    }
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    public com.moshi.im.common.Course getCourse() {
      if (courseBuilder_ == null) {
        return course_ == null ? com.moshi.im.common.Course.getDefaultInstance() : course_;
      } else {
        return courseBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    public Builder setCourse(com.moshi.im.common.Course value) {
      if (courseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        course_ = value;
        onChanged();
      } else {
        courseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    public Builder setCourse(
        com.moshi.im.common.Course.Builder builderForValue) {
      if (courseBuilder_ == null) {
        course_ = builderForValue.build();
        onChanged();
      } else {
        courseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    public Builder mergeCourse(com.moshi.im.common.Course value) {
      if (courseBuilder_ == null) {
        if (course_ != null) {
          course_ =
            com.moshi.im.common.Course.newBuilder(course_).mergeFrom(value).buildPartial();
        } else {
          course_ = value;
        }
        onChanged();
      } else {
        courseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    public Builder clearCourse() {
      if (courseBuilder_ == null) {
        course_ = null;
        onChanged();
      } else {
        course_ = null;
        courseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    public com.moshi.im.common.Course.Builder getCourseBuilder() {
      
      onChanged();
      return getCourseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    public com.moshi.im.common.CourseOrBuilder getCourseOrBuilder() {
      if (courseBuilder_ != null) {
        return courseBuilder_.getMessageOrBuilder();
      } else {
        return course_ == null ?
            com.moshi.im.common.Course.getDefaultInstance() : course_;
      }
    }
    /**
     * <code>.com.moshi.im.common.Course course = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moshi.im.common.Course, com.moshi.im.common.Course.Builder, com.moshi.im.common.CourseOrBuilder> 
        getCourseFieldBuilder() {
      if (courseBuilder_ == null) {
        courseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moshi.im.common.Course, com.moshi.im.common.Course.Builder, com.moshi.im.common.CourseOrBuilder>(
                getCourse(),
                getParentForChildren(),
                isClean());
        course_ = null;
      }
      return courseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.moshi.im.common.CourseIfSubscribedReply)
  }

  // @@protoc_insertion_point(class_scope:com.moshi.im.common.CourseIfSubscribedReply)
  private static final com.moshi.im.common.CourseIfSubscribedReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moshi.im.common.CourseIfSubscribedReply();
  }

  public static com.moshi.im.common.CourseIfSubscribedReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CourseIfSubscribedReply>
      PARSER = new com.google.protobuf.AbstractParser<CourseIfSubscribedReply>() {
    @java.lang.Override
    public CourseIfSubscribedReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CourseIfSubscribedReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CourseIfSubscribedReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CourseIfSubscribedReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moshi.im.common.CourseIfSubscribedReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

