// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

/**
 * Protobuf type {@code com.moshi.im.common.FetchAccountListBaseInfoReply}
 */
public  final class FetchAccountListBaseInfoReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.moshi.im.common.FetchAccountListBaseInfoReply)
    FetchAccountListBaseInfoReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchAccountListBaseInfoReply.newBuilder() to construct.
  private FetchAccountListBaseInfoReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchAccountListBaseInfoReply() {
    account_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FetchAccountListBaseInfoReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              account_ = new java.util.ArrayList<com.moshi.im.common.AccountBaseInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            account_.add(
                input.readMessage(com.moshi.im.common.AccountBaseInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        account_ = java.util.Collections.unmodifiableList(account_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moshi.im.common.FetchAccountListBaseInfoReply.class, com.moshi.im.common.FetchAccountListBaseInfoReply.Builder.class);
  }

  public static final int ACCOUNT_FIELD_NUMBER = 1;
  private java.util.List<com.moshi.im.common.AccountBaseInfo> account_;
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  public java.util.List<com.moshi.im.common.AccountBaseInfo> getAccountList() {
    return account_;
  }
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  public java.util.List<? extends com.moshi.im.common.AccountBaseInfoOrBuilder> 
      getAccountOrBuilderList() {
    return account_;
  }
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  public int getAccountCount() {
    return account_.size();
  }
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  public com.moshi.im.common.AccountBaseInfo getAccount(int index) {
    return account_.get(index);
  }
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  public com.moshi.im.common.AccountBaseInfoOrBuilder getAccountOrBuilder(
      int index) {
    return account_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < account_.size(); i++) {
      output.writeMessage(1, account_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < account_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, account_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moshi.im.common.FetchAccountListBaseInfoReply)) {
      return super.equals(obj);
    }
    com.moshi.im.common.FetchAccountListBaseInfoReply other = (com.moshi.im.common.FetchAccountListBaseInfoReply) obj;

    boolean result = true;
    result = result && getAccountList()
        .equals(other.getAccountList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAccountCount() > 0) {
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccountList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.FetchAccountListBaseInfoReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moshi.im.common.FetchAccountListBaseInfoReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.moshi.im.common.FetchAccountListBaseInfoReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.moshi.im.common.FetchAccountListBaseInfoReply)
      com.moshi.im.common.FetchAccountListBaseInfoReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moshi.im.common.FetchAccountListBaseInfoReply.class, com.moshi.im.common.FetchAccountListBaseInfoReply.Builder.class);
    }

    // Construct using com.moshi.im.common.FetchAccountListBaseInfoReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAccountFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (accountBuilder_ == null) {
        account_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        accountBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_descriptor;
    }

    @java.lang.Override
    public com.moshi.im.common.FetchAccountListBaseInfoReply getDefaultInstanceForType() {
      return com.moshi.im.common.FetchAccountListBaseInfoReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.moshi.im.common.FetchAccountListBaseInfoReply build() {
      com.moshi.im.common.FetchAccountListBaseInfoReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moshi.im.common.FetchAccountListBaseInfoReply buildPartial() {
      com.moshi.im.common.FetchAccountListBaseInfoReply result = new com.moshi.im.common.FetchAccountListBaseInfoReply(this);
      int from_bitField0_ = bitField0_;
      if (accountBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          account_ = java.util.Collections.unmodifiableList(account_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.account_ = account_;
      } else {
        result.account_ = accountBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moshi.im.common.FetchAccountListBaseInfoReply) {
        return mergeFrom((com.moshi.im.common.FetchAccountListBaseInfoReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moshi.im.common.FetchAccountListBaseInfoReply other) {
      if (other == com.moshi.im.common.FetchAccountListBaseInfoReply.getDefaultInstance()) return this;
      if (accountBuilder_ == null) {
        if (!other.account_.isEmpty()) {
          if (account_.isEmpty()) {
            account_ = other.account_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAccountIsMutable();
            account_.addAll(other.account_);
          }
          onChanged();
        }
      } else {
        if (!other.account_.isEmpty()) {
          if (accountBuilder_.isEmpty()) {
            accountBuilder_.dispose();
            accountBuilder_ = null;
            account_ = other.account_;
            bitField0_ = (bitField0_ & ~0x00000001);
            accountBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAccountFieldBuilder() : null;
          } else {
            accountBuilder_.addAllMessages(other.account_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.moshi.im.common.FetchAccountListBaseInfoReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.moshi.im.common.FetchAccountListBaseInfoReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.moshi.im.common.AccountBaseInfo> account_ =
      java.util.Collections.emptyList();
    private void ensureAccountIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        account_ = new java.util.ArrayList<com.moshi.im.common.AccountBaseInfo>(account_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.moshi.im.common.AccountBaseInfo, com.moshi.im.common.AccountBaseInfo.Builder, com.moshi.im.common.AccountBaseInfoOrBuilder> accountBuilder_;

    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public java.util.List<com.moshi.im.common.AccountBaseInfo> getAccountList() {
      if (accountBuilder_ == null) {
        return java.util.Collections.unmodifiableList(account_);
      } else {
        return accountBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public int getAccountCount() {
      if (accountBuilder_ == null) {
        return account_.size();
      } else {
        return accountBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public com.moshi.im.common.AccountBaseInfo getAccount(int index) {
      if (accountBuilder_ == null) {
        return account_.get(index);
      } else {
        return accountBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder setAccount(
        int index, com.moshi.im.common.AccountBaseInfo value) {
      if (accountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountIsMutable();
        account_.set(index, value);
        onChanged();
      } else {
        accountBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder setAccount(
        int index, com.moshi.im.common.AccountBaseInfo.Builder builderForValue) {
      if (accountBuilder_ == null) {
        ensureAccountIsMutable();
        account_.set(index, builderForValue.build());
        onChanged();
      } else {
        accountBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder addAccount(com.moshi.im.common.AccountBaseInfo value) {
      if (accountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountIsMutable();
        account_.add(value);
        onChanged();
      } else {
        accountBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder addAccount(
        int index, com.moshi.im.common.AccountBaseInfo value) {
      if (accountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountIsMutable();
        account_.add(index, value);
        onChanged();
      } else {
        accountBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder addAccount(
        com.moshi.im.common.AccountBaseInfo.Builder builderForValue) {
      if (accountBuilder_ == null) {
        ensureAccountIsMutable();
        account_.add(builderForValue.build());
        onChanged();
      } else {
        accountBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder addAccount(
        int index, com.moshi.im.common.AccountBaseInfo.Builder builderForValue) {
      if (accountBuilder_ == null) {
        ensureAccountIsMutable();
        account_.add(index, builderForValue.build());
        onChanged();
      } else {
        accountBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder addAllAccount(
        java.lang.Iterable<? extends com.moshi.im.common.AccountBaseInfo> values) {
      if (accountBuilder_ == null) {
        ensureAccountIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, account_);
        onChanged();
      } else {
        accountBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder clearAccount() {
      if (accountBuilder_ == null) {
        account_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        accountBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public Builder removeAccount(int index) {
      if (accountBuilder_ == null) {
        ensureAccountIsMutable();
        account_.remove(index);
        onChanged();
      } else {
        accountBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public com.moshi.im.common.AccountBaseInfo.Builder getAccountBuilder(
        int index) {
      return getAccountFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public com.moshi.im.common.AccountBaseInfoOrBuilder getAccountOrBuilder(
        int index) {
      if (accountBuilder_ == null) {
        return account_.get(index);  } else {
        return accountBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public java.util.List<? extends com.moshi.im.common.AccountBaseInfoOrBuilder> 
         getAccountOrBuilderList() {
      if (accountBuilder_ != null) {
        return accountBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(account_);
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public com.moshi.im.common.AccountBaseInfo.Builder addAccountBuilder() {
      return getAccountFieldBuilder().addBuilder(
          com.moshi.im.common.AccountBaseInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public com.moshi.im.common.AccountBaseInfo.Builder addAccountBuilder(
        int index) {
      return getAccountFieldBuilder().addBuilder(
          index, com.moshi.im.common.AccountBaseInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
     */
    public java.util.List<com.moshi.im.common.AccountBaseInfo.Builder> 
         getAccountBuilderList() {
      return getAccountFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.moshi.im.common.AccountBaseInfo, com.moshi.im.common.AccountBaseInfo.Builder, com.moshi.im.common.AccountBaseInfoOrBuilder> 
        getAccountFieldBuilder() {
      if (accountBuilder_ == null) {
        accountBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.moshi.im.common.AccountBaseInfo, com.moshi.im.common.AccountBaseInfo.Builder, com.moshi.im.common.AccountBaseInfoOrBuilder>(
                account_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        account_ = null;
      }
      return accountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.moshi.im.common.FetchAccountListBaseInfoReply)
  }

  // @@protoc_insertion_point(class_scope:com.moshi.im.common.FetchAccountListBaseInfoReply)
  private static final com.moshi.im.common.FetchAccountListBaseInfoReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moshi.im.common.FetchAccountListBaseInfoReply();
  }

  public static com.moshi.im.common.FetchAccountListBaseInfoReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchAccountListBaseInfoReply>
      PARSER = new com.google.protobuf.AbstractParser<FetchAccountListBaseInfoReply>() {
    @java.lang.Override
    public FetchAccountListBaseInfoReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FetchAccountListBaseInfoReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchAccountListBaseInfoReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchAccountListBaseInfoReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moshi.im.common.FetchAccountListBaseInfoReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

