// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public final class ImGrpc {
  private ImGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_AccountBaseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_AccountBaseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_AccountBaseInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_AccountBaseInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_AccountBaseInfoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_AccountBaseInfoReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_FetchAccountListBaseInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_FetchAccountListBaseInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_Waiters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_Waiters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_WaitersReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_WaitersReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_AuthReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_AuthReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_AuthReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_AuthReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_Course_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_Course_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_SubscribedCourseListReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_SubscribedCourseListReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moshi_im_common_SubscribedCourseListReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moshi_im_common_SubscribedCourseListReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010im.proto\022\023com.moshi.im.common\"?\n\017Accou" +
      "ntBaseInfo\022\n\n\002id\030\002 \001(\t\022\020\n\010nickName\030\003 \001(\t" +
      "\022\016\n\006avatar\030\004 \001(\t\" \n\022AccountBaseInfoReq\022\n" +
      "\n\002id\030\001 \001(\t\"\237\001\n\024AccountBaseInfoReply\022\'\n\004c" +
      "ode\030\001 \001(\0162\031.com.moshi.im.common.Code\0225\n\007" +
      "account\030\002 \001(\0132$.com.moshi.im.common.Acco" +
      "untBaseInfo\022\'\n\004role\030\003 \001(\0162\031.com.moshi.im" +
      ".common.Role\")\n\033FetchAccountListBaseInfo" +
      "Req\022\n\n\002id\030\001 \003(\t\"V\n\035FetchAccountListBaseI" +
      "nfoReply\0225\n\007account\030\001 \003(\0132$.com.moshi.im" +
      ".common.AccountBaseInfo\"@\n\007Waiters\0225\n\007ac" +
      "count\030\001 \003(\0132$.com.moshi.im.common.Accoun" +
      "tBaseInfo\"\014\n\nWaitersReq\"$\n\007AuthReq\022\n\n\002id" +
      "\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\"A\n\tAuthReply\022\'\n\004co" +
      "de\030\001 \001(\0162\031.com.moshi.im.common.Code\022\013\n\003m" +
      "sg\030\002 \001(\t\"\205\001\n\006Course\022\n\n\002id\030\001 \001(\005\022\021\n\taccou" +
      "ntId\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\022\n\nshortIntro\030\004" +
      " \001(\t\022\026\n\016introduceImage\030\005 \001(\t\022\022\n\ncourseTy" +
      "pe\030\006 \001(\t\022\016\n\006status\030\007 \001(\005\",\n\027SubscribedCo" +
      "urseListReq\022\021\n\taccountId\030\001 \001(\t\"H\n\031Subscr" +
      "ibedCourseListReply\022+\n\006course\030\001 \003(\0132\033.co" +
      "m.moshi.im.common.Course*\302\003\n\007Command\022\022\n\016" +
      "COMMAND_UNKNOW\020\000\022\032\n\026COMMAND_JOIN_GROUP_R" +
      "EQ\020\005\022\033\n\027COMMAND_JOIN_GROUP_RESP\020\006\022\"\n\036COM" +
      "MAND_JOIN_GROUP_NOTIFY_RESP\020\007\022\"\n\036COMMAND" +
      "_EXIT_GROUP_NOTIFY_RESP\020\010\022\024\n\020COMMAND_CHA" +
      "T_REQ\020\t\022\025\n\021COMMAND_CHAT_RESP\020\n\022\031\n\025COMMAN" +
      "D_HEARTBEAT_REQ\020\017\022\032\n\026COMMAND_HEARTBEAT_R" +
      "ESP\020\020\022\027\n\023COMMAND_REMIND_PUSH\020\032\022\027\n\023COMMAN" +
      "D_ONLINE_PUSH\020\034\022\030\n\024COMMAND_OFFLINE_PUSH\020" +
      "\035\022\034\n\030COMMAND_CLEAR_REMIND_REQ\020\033\022\'\n#COMMA" +
      "ND_ONLINE_NOTIFY_SUBSCRIBE_REQ\020\036\022\024\n\020COMM" +
      "AND_CALL_REQ\020\037\022\025\n\021COMMAND_CALL_RESP\020 *!\n" +
      "\004Code\022\006\n\002OK\020\000\022\021\n\004FAIL\020\377\377\377\377\377\377\377\377\377\001* \n\004Role" +
      "\022\014\n\010CUSTOMER\020\000\022\n\n\006WAITER\020\0012\307\002\n\016AccountSe" +
      "rvice\022c\n\rFetchBaseInfo\022\'.com.moshi.im.co" +
      "mmon.AccountBaseInfoReq\032).com.moshi.im.c" +
      "ommon.AccountBaseInfoReply\022\200\001\n\030FetchAcco" +
      "untListBaseInfo\0220.com.moshi.im.common.Fe" +
      "tchAccountListBaseInfoReq\0322.com.moshi.im" +
      ".common.FetchAccountListBaseInfoReply\022M\n" +
      "\014FetchWaiters\022\037.com.moshi.im.common.Wait" +
      "ersReq\032\034.com.moshi.im.common.Waiters2S\n\013" +
      "AuthService\022D\n\004Auth\022\034.com.moshi.im.commo" +
      "n.AuthReq\032\036.com.moshi.im.common.AuthRepl" +
      "y2\207\001\n\rCourseService\022v\n\026SubscribedCourseL" +
      "istBy\022,.com.moshi.im.common.SubscribedCo" +
      "urseListReq\032..com.moshi.im.common.Subscr" +
      "ibedCourseListReplyB$\n\023com.moshi.im.comm" +
      "onB\006ImGrpcP\001\242\002\002CSb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_moshi_im_common_AccountBaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_moshi_im_common_AccountBaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_AccountBaseInfo_descriptor,
        new java.lang.String[] { "Id", "NickName", "Avatar", });
    internal_static_com_moshi_im_common_AccountBaseInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_moshi_im_common_AccountBaseInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_AccountBaseInfoReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_moshi_im_common_AccountBaseInfoReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_moshi_im_common_AccountBaseInfoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_AccountBaseInfoReply_descriptor,
        new java.lang.String[] { "Code", "Account", "Role", });
    internal_static_com_moshi_im_common_FetchAccountListBaseInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_moshi_im_common_FetchAccountListBaseInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_FetchAccountListBaseInfoReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_FetchAccountListBaseInfoReply_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_moshi_im_common_Waiters_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_moshi_im_common_Waiters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_Waiters_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_moshi_im_common_WaitersReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_moshi_im_common_WaitersReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_WaitersReq_descriptor,
        new java.lang.String[] { });
    internal_static_com_moshi_im_common_AuthReq_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_moshi_im_common_AuthReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_AuthReq_descriptor,
        new java.lang.String[] { "Id", "Token", });
    internal_static_com_moshi_im_common_AuthReply_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_moshi_im_common_AuthReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_AuthReply_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_com_moshi_im_common_Course_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_moshi_im_common_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_Course_descriptor,
        new java.lang.String[] { "Id", "AccountId", "Name", "ShortIntro", "IntroduceImage", "CourseType", "Status", });
    internal_static_com_moshi_im_common_SubscribedCourseListReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_moshi_im_common_SubscribedCourseListReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_SubscribedCourseListReq_descriptor,
        new java.lang.String[] { "AccountId", });
    internal_static_com_moshi_im_common_SubscribedCourseListReply_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_moshi_im_common_SubscribedCourseListReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moshi_im_common_SubscribedCourseListReply_descriptor,
        new java.lang.String[] { "Course", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
