// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface SubscribedCourseListReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.SubscribedCourseListReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accountId = 1;</code>
   */
  int getAccountId();
}
