// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface SubscribedCourseListReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.SubscribedCourseListReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  java.util.List<com.moshi.im.common.Course> 
      getCourseList();
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  com.moshi.im.common.Course getCourse(int index);
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  int getCourseCount();
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  java.util.List<? extends com.moshi.im.common.CourseOrBuilder> 
      getCourseOrBuilderList();
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  com.moshi.im.common.CourseOrBuilder getCourseOrBuilder(
      int index);
}
