// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface SubscriberListOfCourseReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.SubscriberListOfCourseReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  java.util.List<com.moshi.im.common.AccountBaseInfo> 
      getAccountList();
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  com.moshi.im.common.AccountBaseInfo getAccount(int index);
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  int getAccountCount();
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  java.util.List<? extends com.moshi.im.common.AccountBaseInfoOrBuilder> 
      getAccountOrBuilderList();
  /**
   * <code>repeated .com.moshi.im.common.AccountBaseInfo account = 1;</code>
   */
  com.moshi.im.common.AccountBaseInfoOrBuilder getAccountOrBuilder(
      int index);
}
