// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface SubscriberListOfCourseReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.SubscriberListOfCourseReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
