// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface SubscribedCourseListReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.SubscribedCourseListReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountId = 1;</code>
   */
  java.lang.String getAccountId();
  /**
   * <code>string accountId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();
}
