// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

/**
 * Protobuf type {@code com.moshi.im.common.SubscribedCourseListReply}
 */
public  final class SubscribedCourseListReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.moshi.im.common.SubscribedCourseListReply)
    SubscribedCourseListReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribedCourseListReply.newBuilder() to construct.
  private SubscribedCourseListReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribedCourseListReply() {
    course_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubscribedCourseListReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              course_ = new java.util.ArrayList<com.moshi.im.common.Course>();
              mutable_bitField0_ |= 0x00000001;
            }
            course_.add(
                input.readMessage(com.moshi.im.common.Course.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        course_ = java.util.Collections.unmodifiableList(course_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_SubscribedCourseListReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_SubscribedCourseListReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moshi.im.common.SubscribedCourseListReply.class, com.moshi.im.common.SubscribedCourseListReply.Builder.class);
  }

  public static final int COURSE_FIELD_NUMBER = 1;
  private java.util.List<com.moshi.im.common.Course> course_;
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  public java.util.List<com.moshi.im.common.Course> getCourseList() {
    return course_;
  }
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  public java.util.List<? extends com.moshi.im.common.CourseOrBuilder> 
      getCourseOrBuilderList() {
    return course_;
  }
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  public int getCourseCount() {
    return course_.size();
  }
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  public com.moshi.im.common.Course getCourse(int index) {
    return course_.get(index);
  }
  /**
   * <code>repeated .com.moshi.im.common.Course course = 1;</code>
   */
  public com.moshi.im.common.CourseOrBuilder getCourseOrBuilder(
      int index) {
    return course_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < course_.size(); i++) {
      output.writeMessage(1, course_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < course_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, course_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moshi.im.common.SubscribedCourseListReply)) {
      return super.equals(obj);
    }
    com.moshi.im.common.SubscribedCourseListReply other = (com.moshi.im.common.SubscribedCourseListReply) obj;

    boolean result = true;
    result = result && getCourseList()
        .equals(other.getCourseList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCourseCount() > 0) {
      hash = (37 * hash) + COURSE_FIELD_NUMBER;
      hash = (53 * hash) + getCourseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moshi.im.common.SubscribedCourseListReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moshi.im.common.SubscribedCourseListReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.moshi.im.common.SubscribedCourseListReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.moshi.im.common.SubscribedCourseListReply)
      com.moshi.im.common.SubscribedCourseListReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_SubscribedCourseListReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_SubscribedCourseListReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moshi.im.common.SubscribedCourseListReply.class, com.moshi.im.common.SubscribedCourseListReply.Builder.class);
    }

    // Construct using com.moshi.im.common.SubscribedCourseListReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCourseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (courseBuilder_ == null) {
        course_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        courseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moshi.im.common.ImGrpc.internal_static_com_moshi_im_common_SubscribedCourseListReply_descriptor;
    }

    @java.lang.Override
    public com.moshi.im.common.SubscribedCourseListReply getDefaultInstanceForType() {
      return com.moshi.im.common.SubscribedCourseListReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.moshi.im.common.SubscribedCourseListReply build() {
      com.moshi.im.common.SubscribedCourseListReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moshi.im.common.SubscribedCourseListReply buildPartial() {
      com.moshi.im.common.SubscribedCourseListReply result = new com.moshi.im.common.SubscribedCourseListReply(this);
      int from_bitField0_ = bitField0_;
      if (courseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          course_ = java.util.Collections.unmodifiableList(course_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.course_ = course_;
      } else {
        result.course_ = courseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moshi.im.common.SubscribedCourseListReply) {
        return mergeFrom((com.moshi.im.common.SubscribedCourseListReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moshi.im.common.SubscribedCourseListReply other) {
      if (other == com.moshi.im.common.SubscribedCourseListReply.getDefaultInstance()) return this;
      if (courseBuilder_ == null) {
        if (!other.course_.isEmpty()) {
          if (course_.isEmpty()) {
            course_ = other.course_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCourseIsMutable();
            course_.addAll(other.course_);
          }
          onChanged();
        }
      } else {
        if (!other.course_.isEmpty()) {
          if (courseBuilder_.isEmpty()) {
            courseBuilder_.dispose();
            courseBuilder_ = null;
            course_ = other.course_;
            bitField0_ = (bitField0_ & ~0x00000001);
            courseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCourseFieldBuilder() : null;
          } else {
            courseBuilder_.addAllMessages(other.course_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.moshi.im.common.SubscribedCourseListReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.moshi.im.common.SubscribedCourseListReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.moshi.im.common.Course> course_ =
      java.util.Collections.emptyList();
    private void ensureCourseIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        course_ = new java.util.ArrayList<com.moshi.im.common.Course>(course_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.moshi.im.common.Course, com.moshi.im.common.Course.Builder, com.moshi.im.common.CourseOrBuilder> courseBuilder_;

    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public java.util.List<com.moshi.im.common.Course> getCourseList() {
      if (courseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(course_);
      } else {
        return courseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public int getCourseCount() {
      if (courseBuilder_ == null) {
        return course_.size();
      } else {
        return courseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public com.moshi.im.common.Course getCourse(int index) {
      if (courseBuilder_ == null) {
        return course_.get(index);
      } else {
        return courseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder setCourse(
        int index, com.moshi.im.common.Course value) {
      if (courseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCourseIsMutable();
        course_.set(index, value);
        onChanged();
      } else {
        courseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder setCourse(
        int index, com.moshi.im.common.Course.Builder builderForValue) {
      if (courseBuilder_ == null) {
        ensureCourseIsMutable();
        course_.set(index, builderForValue.build());
        onChanged();
      } else {
        courseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder addCourse(com.moshi.im.common.Course value) {
      if (courseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCourseIsMutable();
        course_.add(value);
        onChanged();
      } else {
        courseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder addCourse(
        int index, com.moshi.im.common.Course value) {
      if (courseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCourseIsMutable();
        course_.add(index, value);
        onChanged();
      } else {
        courseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder addCourse(
        com.moshi.im.common.Course.Builder builderForValue) {
      if (courseBuilder_ == null) {
        ensureCourseIsMutable();
        course_.add(builderForValue.build());
        onChanged();
      } else {
        courseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder addCourse(
        int index, com.moshi.im.common.Course.Builder builderForValue) {
      if (courseBuilder_ == null) {
        ensureCourseIsMutable();
        course_.add(index, builderForValue.build());
        onChanged();
      } else {
        courseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder addAllCourse(
        java.lang.Iterable<? extends com.moshi.im.common.Course> values) {
      if (courseBuilder_ == null) {
        ensureCourseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, course_);
        onChanged();
      } else {
        courseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder clearCourse() {
      if (courseBuilder_ == null) {
        course_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        courseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public Builder removeCourse(int index) {
      if (courseBuilder_ == null) {
        ensureCourseIsMutable();
        course_.remove(index);
        onChanged();
      } else {
        courseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public com.moshi.im.common.Course.Builder getCourseBuilder(
        int index) {
      return getCourseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public com.moshi.im.common.CourseOrBuilder getCourseOrBuilder(
        int index) {
      if (courseBuilder_ == null) {
        return course_.get(index);  } else {
        return courseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public java.util.List<? extends com.moshi.im.common.CourseOrBuilder> 
         getCourseOrBuilderList() {
      if (courseBuilder_ != null) {
        return courseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(course_);
      }
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public com.moshi.im.common.Course.Builder addCourseBuilder() {
      return getCourseFieldBuilder().addBuilder(
          com.moshi.im.common.Course.getDefaultInstance());
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public com.moshi.im.common.Course.Builder addCourseBuilder(
        int index) {
      return getCourseFieldBuilder().addBuilder(
          index, com.moshi.im.common.Course.getDefaultInstance());
    }
    /**
     * <code>repeated .com.moshi.im.common.Course course = 1;</code>
     */
    public java.util.List<com.moshi.im.common.Course.Builder> 
         getCourseBuilderList() {
      return getCourseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.moshi.im.common.Course, com.moshi.im.common.Course.Builder, com.moshi.im.common.CourseOrBuilder> 
        getCourseFieldBuilder() {
      if (courseBuilder_ == null) {
        courseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.moshi.im.common.Course, com.moshi.im.common.Course.Builder, com.moshi.im.common.CourseOrBuilder>(
                course_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        course_ = null;
      }
      return courseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.moshi.im.common.SubscribedCourseListReply)
  }

  // @@protoc_insertion_point(class_scope:com.moshi.im.common.SubscribedCourseListReply)
  private static final com.moshi.im.common.SubscribedCourseListReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moshi.im.common.SubscribedCourseListReply();
  }

  public static com.moshi.im.common.SubscribedCourseListReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribedCourseListReply>
      PARSER = new com.google.protobuf.AbstractParser<SubscribedCourseListReply>() {
    @java.lang.Override
    public SubscribedCourseListReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubscribedCourseListReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubscribedCourseListReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscribedCourseListReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moshi.im.common.SubscribedCourseListReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

