// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.moshi.im.common;

public interface WaitersReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moshi.im.common.WaitersReq)
    com.google.protobuf.MessageOrBuilder {
}
