package com.moshi.common.model2.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoupon<M extends BaseCoupon<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 价值
	 */
	public void setValue(java.lang.Double value) {
		set("value", value);
	}
	
	/**
	 * 价值
	 */
	public java.lang.Double getValue() {
		return getDouble("value");
	}

	/**
	 * 折扣或金额券
	 */
	public void setValueType(java.lang.Integer valueType) {
		set("valueType", valueType);
	}
	
	/**
	 * 折扣或金额券
	 */
	public java.lang.Integer getValueType() {
		return getInt("valueType");
	}

	/**
	 * 所属人
	 */
	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	/**
	 * 所属人
	 */
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	/**
	 * 可用于实体，null则通用
	 */
	public void setRefId(java.lang.Integer refId) {
		set("refId", refId);
	}
	
	/**
	 * 可用于实体，null则通用
	 */
	public java.lang.Integer getRefId() {
		return getInt("refId");
	}

	/**
	 * 可用于的实体的类型，course、通用
	 */
	public void setRefType(java.lang.Integer refType) {
		set("refType", refType);
	}
	
	/**
	 * 可用于的实体的类型，course、通用
	 */
	public java.lang.Integer getRefType() {
		return getInt("refType");
	}

	/**
	 * 创建时间
	 */
	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	/**
	 * 过期时间
	 */
	public void setOfferTo(java.lang.Long offerTo) {
		set("offerTo", offerTo);
	}
	
	/**
	 * 过期时间
	 */
	public java.lang.Long getOfferTo() {
		return getLong("offerTo");
	}

	/**
	 * 状态
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
