package com.moshi.common.model2.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 昵称
	 */
	public void setNickName(java.lang.String nickName) {
		set("nickName", nickName);
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	/**
	 * 密码（hash）
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码（hash）
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 手机
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 真实名
	 */
	public void setRealName(java.lang.String realName) {
		set("realName", realName);
	}
	
	/**
	 * 真实名
	 */
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	/**
	 * 身份证号
	 */
	public void setIdentityNumber(java.lang.String identityNumber) {
		set("identityNumber", identityNumber);
	}
	
	/**
	 * 身份证号
	 */
	public java.lang.String getIdentityNumber() {
		return getStr("identityNumber");
	}

	/**
	 * 年龄
	 */
	public void setAge(java.lang.Long age) {
		set("age", age);
	}
	
	/**
	 * 年龄
	 */
	public java.lang.Long getAge() {
		return getLong("age");
	}

	/**
	 * 公司
	 */
	public void setCompany(java.lang.String company) {
		set("company", company);
	}
	
	/**
	 * 公司
	 */
	public java.lang.String getCompany() {
		return getStr("company");
	}

	/**
	 * 职位
	 */
	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	/**
	 * 职位
	 */
	public java.lang.String getPosition() {
		return getStr("position");
	}

	/**
	 * 个人介绍
	 */
	public void setPersonalProfile(java.lang.String personalProfile) {
		set("personalProfile", personalProfile);
	}
	
	/**
	 * 个人介绍
	 */
	public java.lang.String getPersonalProfile() {
		return getStr("personalProfile");
	}

	/**
	 * 性别
	 */
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别
	 */
	public java.lang.String getSex() {
		return getStr("sex");
	}

	/**
	 * 生日
	 */
	public void setBirthday(java.lang.Long birthday) {
		set("birthday", birthday);
	}
	
	/**
	 * 生日
	 */
	public java.lang.Long getBirthday() {
		return getLong("birthday");
	}

	/**
	 * 学历
	 */
	public void setEducation(java.lang.String education) {
		set("education", education);
	}
	
	/**
	 * 学历
	 */
	public java.lang.String getEducation() {
		return getStr("education");
	}

	/**
	 * 行业
	 */
	public void setProfession(java.lang.String profession) {
		set("profession", profession);
	}
	
	/**
	 * 行业
	 */
	public java.lang.String getProfession() {
		return getStr("profession");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	/**
	 * 账号状态
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 账号状态
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setRealPicture(java.lang.String realPicture) {
		set("realPicture", realPicture);
	}
	
	public java.lang.String getRealPicture() {
		return getStr("realPicture");
	}

}
