package com.moshi.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("account", "id", Account.class);
		// Composite Primary Key order: accountId,roleId
		arp.addMapping("account_role", "accountId,roleId", AccountRole.class);
		arp.addMapping("application", "id", Application.class);
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("article_comment", "id", ArticleComment.class);
		arp.addMapping("audio", "id", Audio.class);
		arp.addMapping("auth_code", "id", AuthCode.class);
		arp.addMapping("coupon", "id", Coupon.class);
		arp.addMapping("course", "id", Course.class);
		arp.addMapping("issue", "id", Issue.class);
		arp.addMapping("issue_comment", "id", IssueComment.class);
		arp.addMapping("news", "id", News.class);
		arp.addMapping("paragraph", "id", Paragraph.class);
		arp.addMapping("paragraph_comment", "id", ParagraphComment.class);
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("preset_text", "key", PresetText.class);
		arp.addMapping("recommend", "id", Recommend.class);
		arp.addMapping("role", "id", Role.class);
		// Composite Primary Key order: permissionId,roleId
		arp.addMapping("role_permission", "permissionId,roleId", RolePermission.class);
		arp.addMapping("section", "id", Section.class);
		arp.addMapping("session", "id", Session.class);
		arp.addMapping("subscription", "id", Subscription.class);
		arp.addMapping("video", "id", Video.class);
	}
}

