package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseAccountRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "account_role", primaryKey = "accountId,roleId")
public class AccountRole extends BaseAccountRole<AccountRole> {
	public static final AccountRole dao = new AccountRole().dao();
}
