package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseArticle;

/**
 * Generated by Jboot.
 */
@Table(tableName = "article", primaryKey = "id")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article().dao();
}
