package com.moshi.common.model;

import com.moshi.common.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
  public static final Article dao = new Article().dao();
  public static final int COURSE_ID_FOR_NEWS = -1;

  public static final int STATUS_INIT = 0; // 编辑中
  public static final int STATUS_LOCK = 1; // 锁定
  public static final int STATUS_PUBLISH = 1 << 1; // 发布
  public static final int STATUS_OPEN = 1 << 2; // 试读

}
