package com.moshi.common.model;

import io.jboot.Jboot;
import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseArticleComment;
import io.jboot.support.redis.JbootRedis;

/** Generated by Jboot. */
@Table(tableName = "article_comment", primaryKey = "id")
public class ArticleComment extends BaseArticleComment<ArticleComment> {
  public static final ArticleComment dao = new ArticleComment().dao();

  public static final int STATUS_ORDINARY = 0;
  public static final int STATUS_TOP = 1;

  public int getLikeCount() {
    JbootRedis redis = Jboot.getRedis();
    Integer cnt = redis.get(String.format("article:comment:like:%d", getId()));
    return cnt == null ? 0 : cnt;
  }

  public boolean like(int accountId) {
    JbootRedis redis = Jboot.getRedis();
    boolean has = redis.sismember(String.format("article:comment:liker:%d", getId()), accountId);
    if (!has) {
      redis.incr(String.format("article:comment:like:%d", getId()));
      redis.sadd(String.format("article:comment:liker:%d", getId()), accountId);
    }
    return !has;
  }

  public boolean unlike(int accountId){
    JbootRedis redis = Jboot.getRedis();
    boolean has = redis.sismember(String.format("article:comment:liker:%d", getId()), accountId);
    if (has) {
      redis.decr(String.format("article:comment:like:%d", getId()));
      redis.srem(String.format("article:comment:liker:%d", getId()), accountId);
    }
    return has;
  }
}
