package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseAudio;

/**
 * Generated by Jboot.
 */
@Table(tableName = "audio", primaryKey = "articleId")
public class Audio extends BaseAudio<Audio> {
	public static final Audio dao = new Audio().dao();
}
