package com.moshi.common.model;

import com.moshi.common.model.base.BaseAudio;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Audio extends BaseAudio<Audio> {
  public static final Audio dao=new Audio().dao();
}
