package com.moshi.common.model;

import cn.hutool.core.util.RandomUtil;
import com.jfinal.kit.HashKit;
import com.moshi.common.model.base.BaseCoupon;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coupon extends BaseCoupon<Coupon> {
  public static final Coupon dao = new Coupon().dao();

  public static final int STATUS_USEABLE = 0; // 可用
  public static final int STATUS_TIMEOUT = 1; // 过期
  public static final int STATUS_USED = 2; // 已用

  public static final int REF_TYPE_COMMON = 0; // 通用
  public static final int REF_TYPE_COURSE = 1; // 课程

  public static final int VALUE_TYPE_MONEY = 0; // 直减现金
  public static final int VALUE_TYPE_DISCOUNT = 1; // 折扣

  public static String generateId() {
    return HashKit.sha256(System.currentTimeMillis()+ RandomUtil.randomString(100)).substring(0, 32);
  }
}
