package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseCourse;

/**
 * Generated by Jboot.
 */
@Table(tableName = "course", primaryKey = "id")
public class Course extends BaseCourse<Course> {
	public static final Course dao = new Course().dao();
}
