package com.moshi.common.model;

import com.moshi.common.kit.BitKit;
import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseCourse;

/** Generated by Jboot. */
@Table(tableName = "course", primaryKey = "id")
public class Course extends BaseCourse<Course> {
  public static final Course dao = new Course().dao();

  public static final int STATUS_INIT = 0; // 初始
  public static final int STATUS_LOCK = 1; // 锁定
  public static final int STATUS_PASSED = 1 << 1; // 审核通过
  public static final int STATUS_PUBLISH = 1 << 2; // 发布

  public boolean isInit() {
    return getStatus() == 0;
  }

  public boolean isLock() {
    int status = getStatus();
    return BitKit.at(status, 0) == 1;
  }

  public boolean isPassed() {
    int status = getStatus();
    return BitKit.at(status, 1) == 1;
  }

  public boolean isPublish() {
    int status = getStatus();
    return BitKit.at(status, 2) == 1;
  }

  public void toLock() {
    int status = getStatus();
    status = BitKit.set(status, 0, 1);
    setStatus(status);
    update();
  }

  public void toPassed() {
    int status = getStatus();
    status = BitKit.set(status, 1, 1);
    setStatus(status);
    update();
  }

  public void toPublish() {
    int status = getStatus();
    status = BitKit.set(status, 2, 1);
    setStatus(status);
    update();
  }
}
