package com.moshi.common.model;

import com.moshi.common.model.base.BaseCourseType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseType extends BaseCourseType<CourseType> {
	
}
