package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseIssueComment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "issue_comment", primaryKey = "id")
public class IssueComment extends BaseIssueComment<IssueComment> {
	public static final IssueComment dao = new IssueComment().dao();
}
