package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseIssue;

/** Generated by Jboot. */
@Table(tableName = "issue", primaryKey = "id")
public class Issue extends BaseIssue<Issue> {
  public static final Issue dao = new Issue().dao();

  public static final int STATUS_OPEN = 0;
  public static final int STATUS_CLOSE = 1;
}
