package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseNews;

/**
 * Generated by Jboot.
 */
@Table(tableName = "news", primaryKey = "id")
public class News extends BaseNews<News> {
	public static final News dao = new News().dao();
}
