package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseParagraph;

/**
 * Generated by Jboot.
 */
@Table(tableName = "paragraph", primaryKey = "id")
public class Paragraph extends BaseParagraph<Paragraph> {
	public static final Paragraph dao = new Paragraph().dao();
}
