package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseParagraphComment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "paragraph_comment", primaryKey = "id")
public class ParagraphComment extends BaseParagraphComment<ParagraphComment> {
	public static final ParagraphComment dao = new ParagraphComment().dao();
}
