package com.moshi.common.model;

import com.moshi.common.model.base.BaseParagraph;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Paragraph extends BaseParagraph<Paragraph> {
	
}
