package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BasePermission;

/**
 * Generated by Jboot.
 */
@Table(tableName = "permission", primaryKey = "id")
public class Permission extends BasePermission<Permission> {
	public static final Permission dao = new Permission().dao();
}
