package com.moshi.common.model;

import com.moshi.common.model.base.BasePresetText;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PresetText extends BasePresetText<PresetText> {
	
}
