package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BasePresetText;

/**
 * Generated by Jboot.
 */
@Table(tableName = "preset_text", primaryKey = "key")
public class PresetText extends BasePresetText<PresetText> {
	public static final PresetText dao = new PresetText().dao();
}
