package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseRecommend;

/**
 * Generated by Jboot.
 */
@Table(tableName = "recommend", primaryKey = "id")
public class Recommend extends BaseRecommend<Recommend> {
	public static final Recommend dao = new Recommend().dao();
}
