package com.moshi.common.model;

import com.moshi.common.model.base.BaseRecommend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recommend extends BaseRecommend<Recommend> {
	
}
