package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseRolePermission;

/**
 * Generated by Jboot.
 */
@Table(tableName = "role_permission", primaryKey = "permissionId,roleId")
public class RolePermission extends BaseRolePermission<RolePermission> {
	public static final RolePermission dao = new RolePermission().dao();
}
