package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseSection;

/**
 * Generated by Jboot.
 */
@Table(tableName = "section", primaryKey = "id")
public class Section extends BaseSection<Section> {
	public static final Section dao = new Section().dao();
}
