package com.moshi.common.model;

import io.jboot.db.annotation.Table;
 
import com.moshi.common.model.base.BaseSession;

/**
 * Generated by Jboot.
 */
@Table(tableName = "session", primaryKey = "id")
public class Session extends BaseSession<Session> {
	public static final Session dao = new Session().dao();
	

  private static final long serialVersionUID = 1L; 
  
  /**
   * 登录会话是否已过期
   */
  public boolean isExpired() {
    return getExpireAt() < System.currentTimeMillis();
  }

  /**
   * 登录会话是否未过期
   */
  public boolean notExpired() {
    return ! isExpired();
  }
}
