package com.moshi.common.model;

import cn.hutool.core.util.RandomUtil;
import com.jfinal.kit.HashKit;
import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseSubscription;

import java.util.Date;

/** Generated by Jboot. */
@Table(tableName = "subscription", primaryKey = "id")
public class Subscription extends BaseSubscription<Subscription> {
  public static final Subscription dao = new Subscription().dao();

  public static final int STATUS_INIT = 0; // 未支付
  public static final int STATUS_SUCCESS = 1; // 支付成功
  public static final int STATUS_FAIL = 2; // 支付失败
  public static final int STATUS_CANCEL = 3; // 取消支付

  public static final String SUB_TYPE_COURSE = "course"; // 课程

  public static final int PAY_WAY_QR_TEST = 0; // 二维码支付（测试）
  public static final int PAY_WAY_WX = 1; // 微信支付
  public static final int PAY_WAY_ALIPAY = 2; // 支付宝

  public static String generateId() {
    return HashKit.sha256(new Date().getTime() + RandomUtil.randomString(100)).substring(0, 32);
  }
}
