package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseSubscription;

/**
 * Generated by Jboot.
 */
@Table(tableName = "subscription", primaryKey = "id")
public class Subscription extends BaseSubscription<Subscription> {
	public static final Subscription dao = new Subscription().dao();
}
