package com.moshi.common.model;

import com.moshi.common.model.base.BaseVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Video extends BaseVideo<Video> {
  public static final Video dao=new Video().dao();
}
