package com.moshi.common.model;

import io.jboot.db.annotation.Table;
import com.moshi.common.model.base.BaseVideo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "video", primaryKey = "id")
public class Video extends BaseVideo<Video> {
	public static final Video dao = new Video().dao();
}
